### ISSUE TITLE
`go: downloading` lines after JSON causes panic.

### ISSUE THREAD

**Issue by Sean-Der** [haveyoudebuggedit/gotestfmt#45]
Thank you for this fantastic library! We have been using it for [Pion](https://github.com/pion/webrtc) and has saved me significant time already :) reading test logs without it is terrible.

I am using `go-acc` and in some cases will generate `go: downloading` entries after JSON output. It causes this panic.

```
panic: unexpected output encountered: go: downloading github.com/stretchr/testify v1.7.1 (Did you use -json on go test?)

goroutine 7 [running]:
github.com/haveyoudebuggedit/gotestfmt/v2/parser.parse(0x0?, 0xc000070540, 0xc0000705a0, 0xc000070600, 0xc000070660)
        /home/sean/go/pkg/mod/github.com/haveyoudebuggedit/gotestfmt/v2@v2.3.2/parser/parse.go:165 +0x1125
created by github.com/haveyoudebuggedit/gotestfmt/v2/parser.Parse
        /home/sean/go/pkg/mod/github.com/haveyoudebuggedit/gotestfmt/v2@v2.3.2/parser/parse.go:26 +0x10a
```

In your opinion is this a `gotestfmt` or `go-acc` bug? I have attached a reproduce as well. 
[gotest.log](https://github.com/haveyoudebuggedit/gotestfmt/files/8748234/gotest.log)

**Comment by janosdebugs** [comment]
Hello @Sean-Der thank you very much! This seems to be another case of `go-acc` behaving slightly differently than go test, I couldn't reproduce it with `go test` locally. (Not surprising, since the output is not well documented.)

I have to apologize in advance, this will require some rearchitecting, so I can't fix it as quickly as I usually fix bugs. 

I also wonder to myself if it wouldn't be easier to include code coverage reporting in gotestfmt itself.

**Comment by Sean-Der** [comment]
@janosdebugs no worries here I am not blocked :) `grep -v` has me covered

**Comment by lunemec** [comment]
👋 I ran into similar issue:
```
FAIL	github.com/GlobalWebIndex/core-next/services/permissions/repositories/cache [build failed]
```
causes panic too.

Its ugly because it hides the actual fail, and you have to run it without gotestfmt. This is the exact message:
```
panic: unexpected output encountered: # github.com/GlobalWebIndex/core-next/services/permissions/repositories/cache [github.com/GlobalWebIndex/core-next/services/permissions/repositories/cache.test] (Did you use -json on go test?)

goroutine 7 [running]:
github.com/gotesttools/gotestfmt/v2/parser.parse(0x0?, 0xc000020660, 0xc0000206c0, 0xc000020720, 0xc000020780)
	/home/runner/go/pkg/mod/github.com/gotesttools/gotestfmt/v2@v2.4.1/parser/parse.go:166 +0x1125
created by github.com/gotesttools/gotestfmt/v2/parser.Parse
	/home/runner/go/pkg/mod/github.com/gotesttools/gotestfmt/v2@v2.4.1/parser/parse.go:26 +0x10a
make: *** [Makefile:62: test-go] Error 2
```

**Comment by lunemec** [comment]
Yes, we use https://github.com/stretchr/testify#suite-package but that seems to work for everything - except this that is.
